config/routes.rb
Rails.application.routes.draw do
  resources :properties

  get '/dashboard' => 'dashboard#index'

  devise_for :users, :controllers => {:registrations => "registrations"}

  root 'static_pages#home'

end

app/models/property.rb
class Property < ActiveRecord::Base

  serialize :property_data

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index

    if current_user.blank?
      redirect_to '/'
      return
    end

    @properties = Property.all
    

  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @properties = Property.all
    respond_with(@properties)
  end

  def show
    respond_with(@property)
  end

  def new
    @property = Property.new
    respond_with(@property)
  end

  def edit
  end

  def create

    # abort(property_params.inspect)

    @property = Property.new(property_params)
    @property.save
    
    redirect_to '/dashboard'
  end

  def update
    @property.update(property_params)
    
    redirect_to '/dashboard'
  end

  def destroy
    @property.destroy
    respond_with(@property)
  end

  private
    def set_property
      @property = Property.find(params[:id])
    end

    def property_params
      params.require(:property).permit(:user_id, :coordinate_lat, 
        :coordinate_lng, :name, :property_data => [:date_constructed, :number_of_stories, :comments, :wall_type, :property_use, :roof_type, :window_type,
         :number_of_inhabitants, :number_of_inhabitants_under_twelve, :porch, :windows, :materials_used => []])
    end
end

app/controllers/registrations_controller.rb
# app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    # add  custom create logic here

    if params[:allowed_to_register].blank? or params[:allowed_to_register] != '1'
      flash[:error] = "Please use the special URL provided to register."
      redirect_to '/users/sign_up'
      return
    end

    super
  end

  def update
    super
  end
end 

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home

    if current_user.present?
      redirect_to '/dashboard'
    end

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper

  def property_uses
    [
      'Residential',
      'Commercial',
      'Other',
      'Unknown'
    ]
  end

  def roof_types
    [
      'Flat',
      'Gable',
      'Hip',
      'Composite',
      'Unknown'
    ]
  end

  def window_types
    [
      'None',
      'Single hung',
      'Double hung',
      'Awning',
      'Casement',
      'Hopper',
      'Sliding',
      'Unknown'
    ]
  end

  def wall_types
    [
      'Concrete',
      'Clay brick',
      'Brick',
      'Wood frame',
      'Steel frame'
    ]
  end

  def material_options
    [
      'Fired bricks and clay blocks', 
      'Cement',
      'Fabric',
      'Foam',
      'Glass',
      'Gypcrete',
      'Metal',
      'Plastics',
      'Wood',
      'Other',
      'Unknown'
    ]
  end

  def porch_options
    [
      'No Porch',
      'North',
      'East',
      'South',
      'West',
      'Unknown'
    ]
  end

  def window_options
    [
      'Yes',
      'No',
      'Unknown'
    ]
  end  

end

app/views/dashboard/index.html.erb
<script>

  var myIcon = L.icon({
    iconUrl: "<%= asset_path('marker-icon.png') %>",
    iconRetinaUrl: "<%= asset_path('marker-icon-2x.png') %>",
    shadowUrl: "<%= asset_path('marker-shadow.png') %>",
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41]
  });

</script>


<div id="map" style="width: 100%; height: 100%"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">

    <title>Umap</title>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= params[:controller].gsub('/', '-') %> <%= params[:action] %>">

    <nav class="navbar navbar-default navbar-fixed-top <%= ' hide' if params[:action] == 'home' %>">
      <div class="container">
        <div class="navbar-header">
          
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a href="/dashboard" class="navbar-brand">UMap</a>

        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav pull-right">
            
            <% if current_user.blank? %>
              <li class="<%= ' active' if params[:controller] == 'devise/registrations' and params[:action] == 'new' %>"><a href="/users/sign_up">Sign Up</a></li>
              <li class="<%= ' active' if params[:controller] == 'devise/sessions' and params[:action] == 'new' %>"><a href="/users/sign_in">Sign In</a></li>
            <% else # logged in %>
              <li class="<%= ' active' if params[:controller] == 'dashboard' %>"><a href="/">Map</a></li>
              <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            <% end %>

          </ul>
          
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <%= yield %>

    <nav class="navbar navbar-inverse navbar-fixed-bottom js-alert" style="display: none;">
      <div class="container">
        <p class="navbar-text js-alert-text"></p>
      </div>
    </nav>

  </body>
</html>

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    
    <div class="form-group">
      <%= f.label :name %><br/>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <!-- <div class="form-group">
      <label for="date_constructed">Date Constructed</label><br/>
      <select class="form-control" id="date_constructed" name="property[property_data][date_constructed]">
        <option value="">Select year..</option>
        <option value="Unknown"<%= ' selected' if @property.property_data.present? and @property.property_data['date_constructed'].present? and @property.property_data['date_constructed'] == 'Unknown' %>>Unknown</option>
        <% (1900..(Time.now.year)).each do |year| %>
          <option value="<%= year %>"<%= ' selected' if @property.property_data.present? and @property.property_data['date_constructed'].present? and @property.property_data['date_constructed'].to_i == year %>><%= year %></option>
        <% end %>
      </select>
    </div> -->

    <div class="form-group">
      <label for="date_constructed"># of stories</label><br/>
      <select class="form-control" id="date_constructed" name="property[property_data][number_of_stories]">
        <option value="">Select a number..</option>
        <option value="Unknown"<%= ' selected' if @property.property_data.present? and @property.property_data['number_of_stories'].present? and @property.property_data['number_of_stories'] == 'Unknown' %>>Unknown</option>
        <% (1..50).each do |year| %>
          <option value="<%= year %>"<%= ' selected' if @property.property_data.present? and @property.property_data['number_of_stories'].present? and @property.property_data['number_of_stories'].to_i == year %>><%= year %></option>
        <% end %>
      </select>
    </div>

    <div class="form-group button-list radio-button-list" data-property-field="property_use">
      <label for="date_constructed">Property use?</label><br/>

      <% property_uses.each do |use| %>
        <button type="button" class="btn btn-default<%= ' active' if @property.property_data.present? and @property.property_data['property_use'].present? && @property.property_data['property_use'] == use %>"><%= use %></button>
      <% end %>

      <% if @property.property_data.present? and @property.property_data['property_use'].present? %>
        <input type="hidden" name="property[property_data][property_use]" value="<%= @property.property_data['property_use'] %>" />
      <% end %>

    </div>

    <div class="form-group button-list radio-button-list" data-property-field="roof_type">
      <label for="date_constructed">Roof type</label><br/>

      <% roof_types.each do |roof_type| %>
        <button type="button" class="btn btn-default<%= ' active' if @property.property_data.present? and @property.property_data['roof_type'].present? && @property.property_data['roof_type'] == roof_type %>"><%= roof_type %></button>
      <% end %>

      <% if @property.property_data.present? and @property.property_data['roof_type'].present? %>
        <input type="hidden" name="property[property_data][roof_type]" value="<%= @property.property_data['roof_type'] %>" />
      <% end %>

    </div>

    <div class="form-group button-list radio-button-list" data-property-field="window_type">
      <label for="date_constructed">Window type</label><br/>

      <% window_types.each do |window_type| %>
        <button type="button" class="btn btn-default<%= ' active' if @property.property_data.present? and @property.property_data['window_type'].present? && @property.property_data['window_type'] == window_type %>"><%= window_type %></button>
      <% end %>

      <% if @property.property_data.present? and @property.property_data['window_type'].present? %>
        <input type="hidden" name="property[property_data][window_type]" value="<%= @property.property_data['window_type'] %>" />
      <% end %>

    </div>

    <div class="form-group button-list radio-button-list" data-property-field="wall_type">
      <label for="date_constructed">Wall type</label><br/>

      <% wall_types.each do |wall_type| %>
        <button type="button" class="btn btn-default<%= ' active' if @property.property_data.present? and @property.property_data['wall_type'].present? && @property.property_data['wall_type'] == wall_type %>"><%= wall_type %></button>
      <% end %>

      <% if @property.property_data.present? and @property.property_data['wall_type'].present? %>
        <input type="hidden" name="property[property_data][wall_type]" value="<%= @property.property_data['wall_type'] %>" />
      <% end %>

    </div>

    <div class="form-group button-list radio-button-list" data-property-field="number_of_inhabitants">
      <label for="date_constructed">Total # of inhabitants</label><br/>

      <% (0..20).each do |inhabitant_count| %>
        <button type="button" class="btn btn-default<%= ' active' if @property.property_data.present? and @property.property_data['number_of_inhabitants'].present? and @property.property_data['number_of_inhabitants'] != 'Unknown' && @property.property_data['number_of_inhabitants'].to_i == inhabitant_count %>"><%= inhabitant_count %></button>
      <% end %>

      <button type="button" class="btn btn-default<%= ' active' if @property.property_data.present? and @property.property_data['number_of_inhabitants'].present? and @property.property_data['number_of_inhabitants'] == 'Unknown' %>">Unknown</button>

      <% if @property.property_data.present? and @property.property_data['number_of_inhabitants'].present? %>
        <input type="hidden" name="property[property_data][number_of_inhabitants]" value="<%= @property.property_data['number_of_inhabitants'] %>" />
      <% end %>

    </div>

    <div class="form-group button-list radio-button-list" data-property-field="number_of_inhabitants_under_twelve">
      <label for="date_constructed"># of inhabitants under 12</label><br/>

      <% (0..20).each do |inhabitant_count| %>
        <button type="button" class="btn btn-default<%= ' active' if @property.property_data.present? and @property.property_data['number_of_inhabitants_under_twelve'].present? and @property.property_data['number_of_inhabitants_under_twelve'] != 'Unknown' && @property.property_data['number_of_inhabitants_under_twelve'].to_i == inhabitant_count %>"><%= inhabitant_count %></button>
      <% end %>

      <button type="button" class="btn btn-default<%= ' active' if @property.property_data.present? and @property.property_data['number_of_inhabitants_under_twelve'].present? and @property.property_data['number_of_inhabitants_under_twelve'] == 'Unknown' %>">Unknown</button>

      <% if @property.property_data.present? and @property.property_data['number_of_inhabitants_under_twelve'].present? %>
        <input type="hidden" name="property[property_data][number_of_inhabitants_under_twelve]" value="<%= @property.property_data['number_of_inhabitants_under_twelve'] %>" />
      <% end %>

    </div>

    <div class="form-group button-list radio-button-list" data-property-field="porch">
      <label for="date_constructed">Comments</label><br/>

      <textarea name="property[property_data][comments]" class="form-control"><%= @property.property_data['comments'] if @property.property_data.present? and @property.property_data['comments'].present? %></textarea>

    </div>

  </fieldset>

  <div class="actions">

    <% if params[:action] == 'new' || params[:action] == 'create' %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :coordinate_lat, value: params[:lat] %>
      <%= f.hidden_field :coordinate_lng, value: params[:lng] %>
    <% end %>

    <%= f.submit :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<div class="container">

  <div class="row">

    <div class="col-sm-8 col-sm-offset-2">

      <h1>Editing property</h1>

      <%= render 'form' %>

      <!-- 
      <%= link_to 'Show', @property %> |
      <%= link_to 'Back', properties_path %>
      -->

    </div>

  </div>

</div>

app/views/properties/index.html.erb
<h1>Listing properties</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Coordinate x</th>
      <th>Coordinate y</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.user_id %></td>
        <td><%= property.coordinate_x %></td>
        <td><%= property.coordinate_y %></td>
        <td><%= property.name %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<div class="container">

  <div class="row">

    <div class="col-sm-8 col-sm-offset-2">

      <h1>New property</h1>

      <%= render 'form' %>

    </div>

  </div>

</div>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @property.user_id %>
</p>

<p>
  <strong>Coordinate x:</strong>
  <%= @property.coordinate_x %>
</p>

<p>
  <strong>Coordinate y:</strong>
  <%= @property.coordinate_y %>
</p>

<p>
  <strong>Name:</strong>
  <%= @property.name %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/static_pages/home.html.erb
<div class="site-wrapper">

  <div class="site-wrapper-inner">

    <div class="cover-container">

      <div class="masthead clearfix">
        <div class="inner">
          <h3 class="masthead-brand">UMap</h3>
          <!-- <nav>
            <ul class="nav masthead-nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#">Features</a></li>
              <li><a href="#">Contact</a></li>
            </ul>
          </nav> -->
        </div>
      </div>

      <div class="inner cover">
        <h1 class="cover-heading">Let's map all cities.</h1>
        <p class="lead">Join UMap to help gather data about the unmapped cities of the world. Just because a city is small or poor does not mean it should remain unmapped. Let's change this!</p>
        <p class="lead" style="margin-top: 50px;">
          <a href="/users/sign_in" class="btn btn-lg btn-info btn-sm">Log In</a>
          <!-- <a href="/users/sign_up" class="btn btn-lg btn-success btn-sm">Start Mapping</a> -->
        </p>
      </div>

    </div>

  </div>

</div>